{
  "name": "legacy_WorkspaceDB_mruss_20210709_070243",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/Demo;Contoso 10M",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "Demo",
            "database": "Contoso 10M"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "ServiceAccount",
          "kind": "SQL",
          "path": "demo;Contoso 10M",
          "EncryptConnection": false
        }
      },
      {
        "name": "SQL/Demo;Contoso 10M (legacy)",
        "connectionString": "Data Source=Demo;Initial Catalog=\"Contoso 10M\";Integrated Security=True",
        "impersonationMode": "impersonateServiceAccount",
        "provider": "System.Data.SqlClient",
        "account": "",
        "password": ""
      }
    ],
    "tables": [
      {
        "name": "Customer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name"
          },
          {
            "name": "Address",
            "dataType": "string",
            "sourceColumn": "Address"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "State Code",
            "dataType": "string",
            "sourceColumn": "State Code"
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State"
          },
          {
            "name": "Zip Code",
            "dataType": "string",
            "sourceColumn": "Zip Code"
          },
          {
            "name": "Country Code",
            "dataType": "string",
            "sourceColumn": "Country Code"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country"
          },
          {
            "name": "Birthday",
            "dataType": "dateTime",
            "sourceColumn": "Birthday"
          },
          {
            "name": "Age",
            "dataType": "int64",
            "sourceColumn": "Age"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/Demo;Contoso 10M\",",
                "    dbo_Customer = Source{[Schema=\"dbo\",Item=\"Customer\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_Customer,{\"Continent\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Geography",
            "levels": [
              {
                "name": "Country",
                "ordinal": 0,
                "column": "Country"
              },
              {
                "name": "State or Province",
                "ordinal": 1,
                "column": "State"
              },
              {
                "name": "City",
                "ordinal": 2,
                "column": "City"
              }
            ]
          }
        ]
      },
      {
        "name": "Sales",
        "columns": [
          {
            "name": "Order Number",
            "dataType": "int64",
            "sourceColumn": "Order Number",
            "sourceProviderType": "bigint"
          },
          {
            "name": "Line Number",
            "dataType": "int64",
            "sourceColumn": "Line Number",
            "sourceProviderType": "int"
          },
          {
            "name": "Order Date",
            "dataType": "dateTime",
            "sourceColumn": "Order Date",
            "sourceProviderType": "date"
          },
          {
            "name": "Delivery Date",
            "dataType": "dateTime",
            "sourceColumn": "Delivery Date",
            "sourceProviderType": "date"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey",
            "sourceProviderType": "int"
          },
          {
            "name": "StoreKey",
            "dataType": "int64",
            "sourceColumn": "StoreKey",
            "sourceProviderType": "int"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey",
            "sourceProviderType": "int"
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "sourceColumn": "Quantity",
            "sourceProviderType": "int"
          },
          {
            "name": "Unit Price",
            "dataType": "decimal",
            "sourceColumn": "Unit Price",
            "sourceProviderType": "money"
          },
          {
            "name": "Net Price",
            "dataType": "decimal",
            "sourceColumn": "Net Price",
            "sourceProviderType": "money"
          },
          {
            "name": "Unit Cost",
            "dataType": "decimal",
            "sourceColumn": "Unit Cost",
            "sourceProviderType": "money"
          },
          {
            "name": "Currency Code",
            "dataType": "string",
            "sourceColumn": "Currency Code",
            "sourceProviderType": "nchar"
          },
          {
            "name": "Exchange Rate",
            "dataType": "double",
            "sourceColumn": "Exchange Rate",
            "sourceProviderType": "float"
          },
          {
            "type": "calculated",
            "name": "Line Amount",
            "dataType": "decimal",
            "isDataTypeInferred": true,
            "expression": " Sales[Quantity] * Sales[Net Price]",
            "formatString": "#,0.00"
          }
        ],
        "partitions": [
          {
            "name": "Sales 2011",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "\t*",
                "FROM",
                "\t[dbo].[Sales]",
                "WHERE ",
                "    [Order Date] BETWEEN '2011-01-01' AND '2011-12-31'"
              ],
              "dataSource": "SQL/Demo;Contoso 10M (legacy)"
            },
            "annotations": [
              {
                "name": "TabularEditor_TableSchema",
                "value": "{\"Name\":\"Sales\",\"Schema\":\"dbo\",\"Database\":\"Contoso 10M\",\"IncludedColumns\":[\"Order Number\",\"Line Number\",\"Order Date\",\"Delivery Date\",\"CustomerKey\",\"StoreKey\",\"ProductKey\",\"Quantity\",\"Unit Price\",\"Net Price\",\"Unit Cost\",\"Currency Code\",\"Exchange Rate\"],\"SelectAll\":true}"
              }
            ]
          },
          {
            "name": "Sales 2010",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "\t*",
                "FROM",
                "\t[dbo].[Sales]",
                "WHERE ",
                "    [Order Date] BETWEEN '2010-01-01' AND '2010-12-31'"
              ],
              "dataSource": "SQL/Demo;Contoso 10M (legacy)"
            }
          },
          {
            "name": "Sales 2012",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "\t*",
                "FROM",
                "\t[dbo].[Sales]",
                "WHERE ",
                "    [Order Date] BETWEEN '2012-01-01' AND '2012-12-31'"
              ],
              "dataSource": "SQL/Demo;Contoso 10M (legacy)"
            }
          },
          {
            "name": "Sales 2013",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "\t*",
                "FROM",
                "\t[dbo].[Sales]",
                "WHERE ",
                "    [Order Date] BETWEEN '2013-01-01' AND '2013-12-31'"
              ],
              "dataSource": "SQL/Demo;Contoso 10M (legacy)"
            }
          },
          {
            "name": "Sales 2014",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "\t*",
                "FROM",
                "\t[dbo].[Sales]",
                "WHERE ",
                "    [Order Date] BETWEEN '2014-01-01' AND '2014-12-31'"
              ],
              "dataSource": "SQL/Demo;Contoso 10M (legacy)"
            }
          },
          {
            "name": "Sales 2015",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "\t*",
                "FROM",
                "\t[dbo].[Sales]",
                "WHERE ",
                "    [Order Date] BETWEEN '2015-01-01' AND '2015-12-31'"
              ],
              "dataSource": "SQL/Demo;Contoso 10M (legacy)"
            }
          },
          {
            "name": "Sales 2016",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "\t*",
                "FROM",
                "\t[dbo].[Sales]",
                "WHERE ",
                "    [Order Date] BETWEEN '2016-01-01' AND '2016-12-31'"
              ],
              "dataSource": "SQL/Demo;Contoso 10M (legacy)"
            }
          },
          {
            "name": "Sales 2017",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "\t*",
                "FROM",
                "\t[dbo].[Sales]",
                "WHERE ",
                "    [Order Date] BETWEEN '2017-01-01' AND '2017-12-31'"
              ],
              "dataSource": "SQL/Demo;Contoso 10M (legacy)"
            }
          },
          {
            "name": "Sales 2018",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "\t*",
                "FROM",
                "\t[dbo].[Sales]",
                "WHERE ",
                "    [Order Date] BETWEEN '2018-01-01' AND '2018-12-31'"
              ],
              "dataSource": "SQL/Demo;Contoso 10M (legacy)"
            }
          },
          {
            "name": "Sales 2019",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "\t*",
                "FROM",
                "\t[dbo].[Sales]",
                "WHERE ",
                "    [Order Date] BETWEEN '2019-01-01' AND '2019-12-31'"
              ],
              "dataSource": "SQL/Demo;Contoso 10M (legacy)"
            }
          },
          {
            "name": "Sales 2020",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "\t*",
                "FROM",
                "\t[dbo].[Sales]",
                "WHERE ",
                "    [Order Date] BETWEEN '2020-01-01' AND '2020-12-31'"
              ],
              "dataSource": "SQL/Demo;Contoso 10M (legacy)"
            }
          }
        ],
        "measures": [
          {
            "name": "Sales Amount",
            "expression": [
              " ",
              "SUMX ( Sales, Sales[Quantity] * Sales[Net Price] )"
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "Margin",
            "expression": [
              " SUMX (",
              "    Sales, ",
              "    Sales[Quantity] + ( Sales[Net Price] - Sales[Unit Cost] )",
              ")"
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "Margin %",
            "expression": " [Margin] / [Sales Amount] ",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "Total Cost",
            "expression": " SUMX ( Sales, Sales[Quantity] * Sales[Unit Cost] )",
            "formatString": "#,0.00"
          }
        ]
      },
      {
        "name": "Store",
        "columns": [
          {
            "name": "StoreKey",
            "dataType": "int64",
            "sourceColumn": "StoreKey"
          },
          {
            "name": "Store Code",
            "dataType": "int64",
            "sourceColumn": "Store Code"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country"
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State"
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name"
          },
          {
            "name": "Square Meters",
            "dataType": "int64",
            "sourceColumn": "Square Meters"
          },
          {
            "name": "Open Date",
            "dataType": "dateTime",
            "sourceColumn": "Open Date"
          },
          {
            "name": "Close Date",
            "dataType": "dateTime",
            "sourceColumn": "Close Date"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/Demo;Contoso 10M\",",
                "    dbo_Store = Source{[Schema=\"dbo\",Item=\"Store\"]}[Data]",
                "in",
                "    dbo_Store"
              ]
            }
          }
        ]
      },
      {
        "name": "Date",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          },
          {
            "name": "Year Quarter",
            "dataType": "string",
            "sourceColumn": "Year Quarter"
          },
          {
            "name": "Year Quarter Number",
            "dataType": "int64",
            "sourceColumn": "Year Quarter Number"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter"
          },
          {
            "name": "Year Month",
            "dataType": "string",
            "sourceColumn": "Year Month"
          },
          {
            "name": "Year Month Short",
            "dataType": "string",
            "sourceColumn": "Year Month Short"
          },
          {
            "name": "Year Month Number",
            "dataType": "int64",
            "sourceColumn": "Year Month Number"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month"
          },
          {
            "name": "Month Short",
            "dataType": "string",
            "sourceColumn": "Month Short"
          },
          {
            "name": "Month Number",
            "dataType": "int64",
            "sourceColumn": "Month Number"
          },
          {
            "name": "Day of Week",
            "dataType": "string",
            "sourceColumn": "Day of Week"
          },
          {
            "name": "Day of Week Short",
            "dataType": "string",
            "sourceColumn": "Day of Week Short"
          },
          {
            "name": "Day of Week Number",
            "dataType": "int64",
            "sourceColumn": "Day of Week Number"
          },
          {
            "name": "Working Day",
            "dataType": "boolean",
            "sourceColumn": "Working Day"
          },
          {
            "name": "Working Day Number",
            "dataType": "int64",
            "sourceColumn": "Working Day Number"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/Demo;Contoso 10M\",",
                "    dbo_Date = Source{[Schema=\"dbo\",Item=\"Date\"]}[Data]",
                "in",
                "    dbo_Date"
              ]
            }
          }
        ]
      },
      {
        "name": "Product",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "Product Code",
            "dataType": "string",
            "sourceColumn": "Product Code"
          },
          {
            "name": "Product Name",
            "dataType": "string",
            "sourceColumn": "Product Name"
          },
          {
            "name": "Manufacturer",
            "dataType": "string",
            "sourceColumn": "Manufacturer"
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand"
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color"
          },
          {
            "name": "Weight Unit Measure",
            "dataType": "string",
            "sourceColumn": "Weight Unit Measure"
          },
          {
            "name": "Weight",
            "dataType": "double",
            "sourceColumn": "Weight"
          },
          {
            "name": "Unit Cost",
            "dataType": "decimal",
            "sourceColumn": "Unit Cost"
          },
          {
            "name": "Unit Price",
            "dataType": "decimal",
            "sourceColumn": "Unit Price"
          },
          {
            "name": "Subcategory Code",
            "dataType": "string",
            "sourceColumn": "Subcategory Code"
          },
          {
            "name": "Subcategory",
            "dataType": "string",
            "sourceColumn": "Subcategory"
          },
          {
            "name": "Category Code",
            "dataType": "string",
            "sourceColumn": "Category Code"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/Demo;Contoso 10M\",",
                "    dbo_Product = Source{[Schema=\"dbo\",Item=\"Product\"]}[Data]",
                "in",
                "    dbo_Product"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "3c9a0ba3-3404-4e8c-8e36-99bfa5826470",
        "fromTable": "Sales",
        "fromColumn": "Order Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "54b724b5-52e5-4b72-b159-bbfdebccc247",
        "fromTable": "Sales",
        "fromColumn": "CustomerKey",
        "toTable": "Customer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "4c03235f-5934-4815-b289-6a65e03afe45",
        "fromTable": "Sales",
        "fromColumn": "StoreKey",
        "toTable": "Store",
        "toColumn": "StoreKey"
      },
      {
        "name": "f4190e2b-4ae7-48b3-8b5a-c3707d11d95f",
        "fromTable": "Sales",
        "fromColumn": "ProductKey",
        "toTable": "Product",
        "toColumn": "ProductKey"
      }
    ],
    "cultures": [
      {
        "name": "it-IT",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Customer",
                "translatedCaption": "Cliente"
              }
            ]
          }
        }
      }
    ],
    "roles": [
      {
        "name": "CanadaOnly",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Store",
            "filterExpression": "Store[Country] = \"Canada\""
          },
          {
            "name": "Customer",
            "columnPermissions": [
              {
                "name": "Name",
                "metadataPermission": "none"
              }
            ]
          },
          {
            "name": "Date",
            "filterExpression": "'Date'[Year] = 2018"
          }
        ]
      },
      {
        "name": "FranceOnly",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Store",
            "filterExpression": "Store[Country] = \"France\""
          },
          {
            "name": "Date",
            "filterExpression": "'Date'[Year] = 2019"
          }
        ]
      }
    ],
    "expressions": [
      {
        "name": "Year",
        "kind": "m",
        "expression": "2010 meta [IsParameterQuery=true, Type=\"Number\", IsParameterQueryRequired=true]"
      },
      {
        "name": "SalesOneYear",
        "kind": "m",
        "expression": [
          "let",
          "    Source = (Year as number) => let",
          "        Source = #\"SQL/Demo;Contoso 10M\",",
          "        dbo_Sales = Source{[Schema=\"dbo\",Item=\"Sales\"]}[Data],",
          "        #\"Filtered Rows\" = Table.SelectRows(dbo_Sales, each Date.Year([Order Date]) = Year)",
          "    in",
          "        #\"Filtered Rows\"",
          "in",
          "    Source"
        ]
      },
      {
        "name": "Sales2010",
        "kind": "m",
        "expression": [
          "let",
          "    Source = SalesOneYear(2010)",
          "in",
          "    Source"
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[]}"
      }
    ]
  }
}