{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/Demo;Contoso 1M",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "Demo",
            "database": "Contoso 1M"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "ServiceAccount",
          "kind": "SQL",
          "path": "demo;Contoso 1M",
          "EncryptConnection": false
        }
      },
      {
        "name": "SqlServer Demo Contoso 1M",
        "connectionString": "Provider=SQLNCLI11;Data Source=Demo;Initial Catalog=Contoso 1M;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Customer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name"
          },
          {
            "name": "Address",
            "dataType": "string",
            "sourceColumn": "Address"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "State Code",
            "dataType": "string",
            "sourceColumn": "State Code"
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State"
          },
          {
            "name": "Zip Code",
            "dataType": "string",
            "sourceColumn": "Zip Code"
          },
          {
            "name": "Country Code",
            "dataType": "string",
            "sourceColumn": "Country Code"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country"
          },
          {
            "name": "Birthday",
            "dataType": "dateTime",
            "sourceColumn": "Birthday"
          },
          {
            "name": "Age",
            "dataType": "int64",
            "sourceColumn": "Age"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/Demo;Contoso 1M\",",
                "    dbo_Customer = Source{[Schema=\"dbo\",Item=\"Customer\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_Customer,{\"Continent\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Geography",
            "levels": [
              {
                "name": "Country",
                "ordinal": 0,
                "column": "Country"
              },
              {
                "name": "State or Province",
                "ordinal": 1,
                "column": "State"
              },
              {
                "name": "City",
                "ordinal": 2,
                "column": "City"
              }
            ]
          }
        ]
      },
      {
        "name": "Store",
        "columns": [
          {
            "name": "StoreKey",
            "dataType": "int64",
            "sourceColumn": "StoreKey"
          },
          {
            "name": "Store Code",
            "dataType": "int64",
            "sourceColumn": "Store Code"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country"
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State"
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name"
          },
          {
            "name": "Square Meters",
            "dataType": "int64",
            "sourceColumn": "Square Meters"
          },
          {
            "name": "Open Date",
            "dataType": "dateTime",
            "sourceColumn": "Open Date"
          },
          {
            "name": "Close Date",
            "dataType": "dateTime",
            "sourceColumn": "Close Date"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/Demo;Contoso 1M\",",
                "    dbo_Store = Source{[Schema=\"dbo\",Item=\"Store\"]}[Data]",
                "in",
                "    dbo_Store"
              ]
            }
          }
        ]
      },
      {
        "name": "Date",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          },
          {
            "name": "Year Quarter",
            "dataType": "string",
            "sourceColumn": "Year Quarter"
          },
          {
            "name": "Year Quarter Number",
            "dataType": "int64",
            "sourceColumn": "Year Quarter Number"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter"
          },
          {
            "name": "Year Month",
            "dataType": "string",
            "sourceColumn": "Year Month"
          },
          {
            "name": "Year Month Short",
            "dataType": "string",
            "sourceColumn": "Year Month Short"
          },
          {
            "name": "Year Month Number",
            "dataType": "int64",
            "sourceColumn": "Year Month Number"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month"
          },
          {
            "name": "Month Short",
            "dataType": "string",
            "sourceColumn": "Month Short"
          },
          {
            "name": "Month Number",
            "dataType": "int64",
            "sourceColumn": "Month Number"
          },
          {
            "name": "Day of Week",
            "dataType": "string",
            "sourceColumn": "Day of Week"
          },
          {
            "name": "Day of Week Short",
            "dataType": "string",
            "sourceColumn": "Day of Week Short"
          },
          {
            "name": "Day of Week Number",
            "dataType": "int64",
            "sourceColumn": "Day of Week Number"
          },
          {
            "name": "Working Day",
            "dataType": "boolean",
            "sourceColumn": "Working Day"
          },
          {
            "name": "Working Day Number",
            "dataType": "int64",
            "sourceColumn": "Working Day Number"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/Demo;Contoso 1M\",",
                "    dbo_Date = Source{[Schema=\"dbo\",Item=\"Date\"]}[Data]",
                "in",
                "    dbo_Date"
              ]
            }
          }
        ]
      },
      {
        "name": "Product",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "Product Code",
            "dataType": "string",
            "sourceColumn": "Product Code"
          },
          {
            "name": "Product Name",
            "dataType": "string",
            "sourceColumn": "Product Name"
          },
          {
            "name": "Manufacturer",
            "dataType": "string",
            "sourceColumn": "Manufacturer"
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand"
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color"
          },
          {
            "name": "Weight Unit Measure",
            "dataType": "string",
            "sourceColumn": "Weight Unit Measure"
          },
          {
            "name": "Weight",
            "dataType": "double",
            "sourceColumn": "Weight"
          },
          {
            "name": "Unit Cost",
            "dataType": "decimal",
            "sourceColumn": "Unit Cost"
          },
          {
            "name": "Unit Price",
            "dataType": "decimal",
            "sourceColumn": "Unit Price"
          },
          {
            "name": "Subcategory Code",
            "dataType": "string",
            "sourceColumn": "Subcategory Code"
          },
          {
            "name": "Subcategory",
            "dataType": "string",
            "sourceColumn": "Subcategory"
          },
          {
            "name": "Category Code",
            "dataType": "string",
            "sourceColumn": "Category Code"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/Demo;Contoso 1M\",",
                "    dbo_Product = Source{[Schema=\"dbo\",Item=\"Product\"]}[Data]",
                "in",
                "    dbo_Product"
              ]
            }
          }
        ]
      },
      {
        "name": "Sales",
        "columns": [
          {
            "name": "Order Number",
            "dataType": "int64",
            "sourceColumn": "Order Number",
            "sourceProviderType": "BigInt"
          },
          {
            "name": "Line Number",
            "dataType": "int64",
            "sourceColumn": "Line Number",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Order Date",
            "dataType": "dateTime",
            "sourceColumn": "Order Date",
            "formatString": "General Date",
            "sourceProviderType": "DBDate"
          },
          {
            "name": "Delivery Date",
            "dataType": "dateTime",
            "sourceColumn": "Delivery Date",
            "formatString": "General Date",
            "sourceProviderType": "DBDate"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "StoreKey",
            "dataType": "int64",
            "sourceColumn": "StoreKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "sourceColumn": "Quantity",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Unit Price",
            "dataType": "decimal",
            "sourceColumn": "Unit Price",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Net Price",
            "dataType": "decimal",
            "sourceColumn": "Net Price",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Unit Cost",
            "dataType": "decimal",
            "sourceColumn": "Unit Cost",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Currency Code",
            "dataType": "string",
            "sourceColumn": "Currency Code",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Exchange Rate",
            "dataType": "double",
            "sourceColumn": "Exchange Rate",
            "sourceProviderType": "Double"
          }
        ],
        "partitions": [
          {
            "name": "Sales 2011 and more",
            "source": {
              "type": "query",
              "query": "SELECT [dbo].[Sales].* FROM [dbo].[Sales]  WHERE ([Order Date] >= N'2011-01-01 00:00:00')",
              "dataSource": "SqlServer Demo Contoso 1M"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Order Number</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>142</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Line Number</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>130</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Order Date</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>117</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Delivery Date</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>133</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CustomerKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>132</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>StoreKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>101</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ProductKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>118</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Quantity</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>99</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Unit Price</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>107</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Net Price</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>102</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Unit Cost</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>104</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Currency Code</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>143</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Exchange Rate</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>142</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Order Number</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Line Number</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Order Date</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Delivery Date</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CustomerKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>StoreKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ProductKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Quantity</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Unit Price</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Net Price</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Unit Cost</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Currency Code</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Exchange Rate</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked />",
                  "  <ColumnFilter>",
                  "    <item>",
                  "      <key>",
                  "        <string>Order Date</string>",
                  "      </key>",
                  "      <value>",
                  "        <FilterExpression xsi:type=\"ConditionalExpression\">",
                  "          <Operator>AfterOrEqual</Operator>",
                  "          <Value xsi:type=\"xsd:dateTime\">2011-01-01T00:00:00</Value>",
                  "        </FilterExpression>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnFilter>",
                  "  <SelectionFilter>",
                  "    <item>",
                  "      <key>",
                  "        <string>Order Date</string>",
                  "      </key>",
                  "      <value>",
                  "        <SelectionFilter xsi:nil=\"true\" />",
                  "      </value>",
                  "    </item>",
                  "  </SelectionFilter>",
                  "  <FilterParameters>",
                  "    <item>",
                  "      <key>",
                  "        <string>Order Date</string>",
                  "      </key>",
                  "      <value>",
                  "        <CommandParameters />",
                  "      </value>",
                  "    </item>",
                  "  </FilterParameters>",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Sales 2010",
            "mode": "import",
            "source": {
              "type": "query",
              "query": [
                "SELECT [dbo].[Sales].* FROM [dbo].[Sales]  ",
                "WHERE (([Order Date] >= N'2010-01-01 00:00:00') AND ([Order Date] < N'2011-01-01 00:00:00'))"
              ],
              "dataSource": "SqlServer Demo Contoso 1M"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[Sales].* FROM [dbo].[Sales]  ",
                  "WHERE (([Order Date] >= N'2010-01-01 00:00:00') AND ([Order Date] < N'2011-01-01 00:00:00'))</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Sales Amount",
            "expression": [
              " ",
              "SUMX ( Sales, Sales[Quantity] * Sales[Net Price] )"
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "Margin",
            "expression": [
              " SUMX (",
              "    Sales, ",
              "    Sales[Quantity] + ( Sales[Net Price] - Sales[Unit Cost] )",
              ")"
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "Margin %",
            "expression": " [Margin] / [Sales Amount] ",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "Total Cost",
            "expression": " SUMX ( Sales, Sales[Quantity] * Sales[Unit Cost] )",
            "formatString": "#,0.00"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Sales].* FROM [dbo].[Sales] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sales"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "a83d5f14-61ee-4252-a382-74161d891066",
        "fromTable": "Sales",
        "fromColumn": "CustomerKey",
        "toTable": "Customer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "857010b9-d9a5-40d6-80fd-f40bb348fcdb",
        "fromTable": "Sales",
        "fromColumn": "Order Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "445eef94-2065-425a-895c-96ced36e3128",
        "fromTable": "Sales",
        "fromColumn": "StoreKey",
        "toTable": "Store",
        "toColumn": "StoreKey"
      },
      {
        "name": "dbf4faff-1474-4c2a-ba1d-6614f037c680",
        "fromTable": "Sales",
        "fromColumn": "ProductKey",
        "toTable": "Product",
        "toColumn": "ProductKey"
      }
    ],
    "cultures": [
      {
        "name": "it-IT",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Customer",
                "translatedCaption": "Cliente"
              }
            ]
          }
        }
      }
    ],
    "roles": [
      {
        "name": "CanadaOnly",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Store",
            "filterExpression": "Store[Country] = \"Canada\""
          },
          {
            "name": "Customer",
            "columnPermissions": [
              {
                "name": "Name",
                "metadataPermission": "none"
              }
            ]
          },
          {
            "name": "Date",
            "filterExpression": "'Date'[Year] = 2018"
          }
        ]
      },
      {
        "name": "FranceOnly",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Store",
            "filterExpression": "Store[Country] = \"France\""
          },
          {
            "name": "Date",
            "filterExpression": "'Date'[Year] = 2019"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}